### ISSUE TITLE
Please clean up your requirements.

### ISSUE THREAD

**Issue by amcgregor** [kevinadhiguna/link-shortener#1]
# Your package does not have 231 dependencies.

`short.py` only has one real dependency: `pyshorteners` — and is little more than:

```sh
python -me 'import pyshorteners; pyshorteners.Shortener().tinyurl.short("http://example.com/")'
```

Please remove the entirety of your `requirements.txt` declaration, it is spamming up the "dependants" listing for every single one of the referenced projects, and is unnecessary if the dependencies are correctly declared in `setup.py` or `setup.cfg`.

Thank you.

**Comment by kevinadhiguna** [comment]
Hello @amcgregor , thank you very much for this report. I assume [the latest commit](https://github.com/kevinadhiguna/link-shortener/commit/4255b013d0d4fdc40f3793af147193a1f4a80f13) should fix this issue. However, do not hesitate to tell me if the problem still exists, thank you !

**Comment by amcgregor** [comment]
Thank you very much, and apologies for the cross-project e-mail notification spam I must have triggered; thought you may wish to individually track corrections.

Thank you again! (Time for another spam-wave. 😭) ×3
